# Generated by Django 6.0.6 on 2026-07-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cart_product_alter_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
